DROP DATABASE IF EXISTS shopdb;
DROP USER IF EXISTS `shopadmin`@`%`;
DROP USER IF EXISTS `shopuser`@`%`;
CREATE DATABASE IF NOT EXISTS shopdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `shopadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `shopdb`.* TO `shopadmin`@`%`;
CREATE USER IF NOT EXISTS `shopuser`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `shopdb`.* TO `shopuser`@`%`;
FLUSH PRIVILEGES;